name: Build Github Demo
on: push

jobs:
  Explore-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
      - name: Build GitHub Demo with Maven
        working-directory: GitHubDemo
      - run: mvn -B clean install --file pom.xml
      