name: Build Github Demo
on:
  push:
    branches: [ $default-branch ]

defaults:
  run:
    working-directory: ./GitHubDemo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
          run:  mvn -B clean install --file pom.xml
