name: Build Github Demo
on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
              cache: maven
      - name: Build GitHub Demo with Maven
          working-directory: GitHubDemo
          run: mvn -B clean install --file pom.xml
      